[project]
name = "sleepremover"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Victor De Lomas", email = "victordlp8@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"
